title: "vessel"
email: snapbackvessel17@gmail.com
description: >-
  snapback home base

remote_theme: pages-themes/minimal@v0.2.0

permalink: /:title/
baseurl: "" 
url: "https://vessel.momentismedical.dev"

collections:
  posts:
    output: true

plugins:
  - jekyll-gist
  - jekyll-remote-theme
